# Generated by Django 5.2.1 on 2026-01-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transnet_mobility', '0033_add_urgency_level_to_maintenanceschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='on_leave_until',
            field=models.DateTimeField(blank=True, help_text='Date and time when user should return from leave (auto-reset to available)', null=True),
        ),
    ]
